### ISSUE TITLE
Suggest change for reduce

### ISSUE THREAD

**Issue by placoderm** [ayushgptaa/Web-tools#1]
I'd suggest changing this 

`['🍎', '🍌', '🍇'].reduce((acc, cur) => acc + cur, '🍌'); //Reduce the values of an array to a single value, output: "🍌🍎🍌🍇"//`

to this
`['🍎', '🍌', '🍇'].reduce((acc, cur) => acc + cur, '🍒'); //Reduce the values of an array to a single value, output: "🍒🍎🍌🍇"//`

because it is more clear. In the first version, there can be some confusion about the 🍌 being there twice.

This is an awesome document. I made my own version as a pdf with the code and the output in coulums next to each other. I'm happy to share if you like.

Thanks so much!!

**Comment by ayushgptaa** [comment]
Yes, this is definitely more clear. Thanks for this and you can also add your pdf to the repository, I would love to see it and it could be helpful for others.

**Comment by ayushgptaa** [comment]
@placoderm I think you want to add changes to this repository, this is the wrong one😅  https://github.com/ayushgptaa/Javascript-Array-cheatsheet

Yes, this is definitely more clear. Thanks for this and you can also add your pdf to the repository, I would love to see it and it could be helpful for others 😄

**Comment by placoderm** [comment]
Oh, sorry. I must have gotten confused looking around your repos. Feel free to delete.


I also thought this might be an improvement:
`['🍎','🍌','🍇','🍒'].fill('🍑',2,3) // fill all the array elements with "🍑", output ['🍎','🍑','🍑','🍒']`

The example you have appears to be a little useless, although they are all by necessity a little contrived.

I'm still working on it, but here is a draft: https://ufile.io/h4f6ptve

It seems that there is some issue with Word/LibreOffice in creating pdfs that include colour emojis. 

Thanks so much!

**Comment by ayushgptaa** [comment]
Thanks, keep suggesting the improvements, or you can contribute changes directly to the repository. And one more thing, it's not opening for me, could you probably share via any other link (maybe google drive or something).

Thank you so much and have an awesome day :)
